@startuml user
class User {
    String name
    String id
    String username 
    String pasword
}

enum Type {
    STANDARD
    ADMIN
}

User --> Type

class History {
    String action 
    LocalDateTime Date
}

User -- History

@enduml